In [49]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import linear_model
%matplotlib inline

In [50]:
df=sns.load_dataset('titanic')

In [51]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [52]:
df1=df.iloc[:,[0,2]]

In [53]:
df1.head()

survived     sex
0         0    male
1         1  female
2         1  female
3         1  female
4         0    male

# Using pandas to create dummy variables

In [54]:
dm=pd.get_dummies(df1.sex,drop_first=True) 
#droping first column to avoid dummy trap(cause Multicollinearity)

In [55]:
dm.head()

male
0     1
1     0
2     0
3     0
4     1

In [56]:
#concat dummy variable(column) with rest of the dataframe and droping parent column of dummy variable column
df2=pd.concat([df1,dm],axis='columns')
df2=df2.drop('sex',axis='columns')

In [57]:
df2.head()

survived  male
0         0     1
1         1     0
2         1     0
3         1     0
4         0     1

In [58]:
y=df2['survived']
x=df2.drop('survived',axis='columns')

In [59]:
#training model
reg=LinearRegression()
reg.fit(x,y)

<IPython.core.display.Javascript object>

LinearRegression()

In [60]:
reg.predict([[0]])

C:\Users\welcome\anaconda3\lib\site-packages\sklearn\base.py:409: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([0.74203822])

# OneHotEncoding

### 1) label Encoder

In [61]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [63]:
dfle=df1
dfle.loc[:,'sex']=le.fit_transform(dfle.loc[:,'sex'])
dfle

C:\Users\welcome\AppData\Local\Temp\ipykernel_2384\447253159.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfle.loc[:,'sex']=le.fit_transform(dfle.loc[:,'sex'])


survived  sex
0           0    1
1           1    0
2           1    0
3           1    0
4           0    1
..        ...  ...
886         0    1
887         1    0
888         0    0
889         1    1
890         0    1

[891 rows x 2 columns]

In [67]:
# converting into matrix
X=dfle[['sex']].values
X

array([[1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
    

In [88]:
Y=dfle[['survived']]

### 2) applying OneHotEncoder

In [79]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer(transformers=[('sex',OneHotEncoder(drop='first'),[0])],remainder='passthrough')

In [81]:
X=ct.fit_transform(X)
x

male
0       1
1       0
2       0
3       0
4       1
..    ...
886     1
887     0
888     0
889     1
890     1

[891 rows x 1 columns]

In [83]:
lr=LinearRegression()
lr.fit(X,Y)

<IPython.core.display.Javascript object>

LinearRegression()

In [86]:
lr.predict([[0]])

array([[0.74203822]])