In [195]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.datasets import load_wine
%matplotlib inline

In [196]:
df=pd.read_csv('spam.csv',encoding='latin-1')
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham              Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [197]:
df.rename(columns={'Category':'v1','Message':'v2'},inplace=True)

In [198]:
df

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [199]:
df.loc[:,'v1']=df.loc[:,'v1'].apply(lambda x:1 if x=='spam' else 0)
df

v1                                                 v2
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...
...   ..                                                ...
5567   1  This is the 2nd time we have tried 2 contact u...
5568   0              Will ü b going to esplanade fr home?
5569   0  Pity, * was in mood for that. So...any other s...
5570   0  The guy did some bitching but I acted like i'd...
5571   0                         Rofl. Its true to its name

[5572 rows x 2 columns]

### Splitting training and test dataset

In [200]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df['v2'],df['v1'],test_size=0.2)

In [201]:
x_test

933                    So do you have samus shoulders yet
3548    Rock yr chik. Get 100's of filthy films &XXX p...
2157    Hey cutie. How goes it? Here in WALES its kind...
5129    Rose for red,red for blood,blood for heart,hea...
3541    I'll get there at 3, unless you guys want me t...
                              ...                        
2838                              1's reach home call me.
1273                                                Ok...
1363                        What does the dance river do?
3352                         At what time are you coming.
1481                    Have you always been saying welp?
Name: v2, Length: 1115, dtype: object

In [202]:
x_train

923     It shall be fine. I have avalarr now. Will hol...
4931    Hi, the SEXYCHAT girls are waiting for you to ...
2972    Height of Confidence: All the Aeronautics prof...
1504                      Ill be there on  &lt;#&gt;  ok.
1177    Did he say how fantastic I am by any chance, o...
                              ...                        
5034    * Was really good to see you the other day dud...
4836    OH RITE. WELL IM WITH MY BEST MATE PETE, WHO I...
3259    He fucking chickened out. He messaged me he wo...
794     Omg I want to scream. I weighed myself and I l...
4686    Alright we'll bring it to you, see you in like...
Name: v2, Length: 4457, dtype: object

## Count Vectorizer

In [203]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
x_train_count=cv.fit_transform(x_train.values)
x_train_count.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

# multinomial NAIVE BAYES classifier

In [204]:
from sklearn.naive_bayes import MultinomialNB
nv=MultinomialNB()
nv.fit(x_train_count,y_train)

MultinomialNB()

In [220]:
#testing
email=['Hey mohan, can we get together to watch footbal game tomorrow?','Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!']
em=cv.transform(email)  # everytime before we predict we have to transform the text
nv.predict(em)

array([0, 1], dtype=int64)

#### everytime before we predict we have to transform the text

In [221]:
x_test_count=cv.transform(x_test.values)
nv.predict(x_test_count)

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [207]:
nv.score(x_test_count,y_test)

0.9847533632286996

## Pipeline

In [214]:
from sklearn.pipeline import Pipeline
pi=Pipeline([
    ('cv',CountVectorizer()),
    ('nv',MultinomialNB())]
)

In [216]:
pi.fit(x_train,y_train)

Pipeline(steps=[('cv', CountVectorizer()), ('nv', MultinomialNB())])

In [217]:
pi.predict(x_test)

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [218]:
pi.score(x_test,y_test)

0.9847533632286996

📎 more about pipline